@startuml

[*] --> Ready

state Ready {
    note "One nested finite-state machine per ledger" as NestedFsmForReadyState

    [*] --> Idle

    Idle --> Checking : CheckIfLedgerLagged(x) / request LedgerStatuses(x) from others

    state Checking_LedgerStatus <<choice>>
    Checking --> Checking_LedgerStatus : LedgerStatus(x)

    state Checking_LedgerStatus_Newer <<choice>>
    Checking_LedgerStatus --> Checking_LedgerStatus_Newer : [newer]
    state Checking_LedgerStatus_NotNewer <<choice>>
    Checking_LedgerStatus --> Checking_LedgerStatus_NotNewer : [not newer]

    Checking_LedgerStatus_Newer --> Checking : [did not gather f+1 newer LSes(x)]
    Checking_LedgerStatus_Newer --> Idle : [gathered f+1 newer LSes(x)] / StartCatchup

    Checking_LedgerStatus_NotNewer --> Checking : [did not gather n-f-1 not newer LSes(x)]
    Checking_LedgerStatus_NotNewer --> Idle : [gathered n-f-1 not newer LSes(x)]
}

Ready --> CatchingUpLedgers : StartCatchup / lastTxn3PCs = []; StartLedgerCatchup(0)

state CatchingUpLedgers_LedgerCatchupFinished <<choice>>
CatchingUpLedgers --> CatchingUpLedgers_LedgerCatchupFinished : LedgerCatchupFinished(i, lastTxn3PC) / lastTxn3PCs.append(lastTxn3PC)

CatchingUpLedgers_LedgerCatchupFinished --> CatchingUpLedgers : [i+1 < len(ledgers)] / StartLedgerCatchup(i+1)
CatchingUpLedgers_LedgerCatchupFinished --> Ready : [i+1 == len(ledgers)] / last3PC = max(lastTxn3PCs); CatchupFinished(last3PC)

@enduml
