@startuml

[*] --> Active

state Active {
    [*] --> LedgerStatusServantActive

    LedgerStatusServantActive --> LedgerStatusServantActive : Request for LedgerStatus / send LedgerStatus
    state LedgerStatusServantActive_LS <<choice>>
    LedgerStatusServantActive --> LedgerStatusServantActive_LS : LedgerStatus

    LedgerStatusServantActive_LS --> LedgerStatusServantActive : [older] / send ConsistencyProof
    LedgerStatusServantActive_LS --> LedgerStatusServantActive : [same]
    LedgerStatusServantActive_LS --> LedgerStatusServantActive : [newer] / send CheckIfLedgerLagged(ledgerId)
    --

    [*] --> ConsistencyProofServantActive

    state ConsistencyProofServantActive_ReqForCP <<choice>>
    ConsistencyProofServantActive --> ConsistencyProofServantActive_ReqForCP : Request for ConsistencyProof(..., end)
    state ConsistencyProofServantActive_CP <<choice>>
    ConsistencyProofServantActive --> ConsistencyProofServantActive_CP : ConsistencyProof

    ConsistencyProofServantActive_ReqForCP --> ConsistencyProofServantActive : [end <= ledger.size] / send ConsistencyProof(..., end)
    ConsistencyProofServantActive_ReqForCP --> ConsistencyProofServantActive : [end > ledger.size]

    ConsistencyProofServantActive_CP --> ConsistencyProofServantActive : [end <= ledger.size]
    ConsistencyProofServantActive_CP --> ConsistencyProofServantActive : [end > ledger.size] / send CheckIfLedgerLagged(ledgerId)
    --

    [*] --> CatchupReqServantActive

    state CatchupReqServantActive_CatchupReq <<choice>>
    CatchupReqServantActive --> CatchupReqServantActive_CatchupReq : CatchupReq(..., catchUpTill)

    CatchupReqServantActive_CatchupReq --> CatchupReqServantActive : [catchUpTill <= ledger.size] / send CatchupRep(...)
    CatchupReqServantActive_CatchupReq --> CatchupReqServantActive : [catchUpTill > ledger.size]
}

@enduml
