import base58

VALID_BASE58 = base58.alphabet.decode("utf-8")

TEST_TARGET_NYM = 'HebGWgHmicPtzr4BTHmSmXkDNL7CngDjYVcxqT5oprMw'

TEST_VERKEY_ABBREVIATED = '~A43KHjJmjwFX71J1b5p61N'
TEST_VERKEY_FULL = 'ED6cb1vtM8JEReLzUFnuGMZX4jt9jnEuDfwGTiAcARtD'

TEST_IDENTIFIER_LONG = 'EJC3Gg4J2PqATnMn2b94VTn1tm7Ygr1SfttzPp8QdXJ6'
TEST_IDENTIFIER_SHORT = '5gC6mJq5MoGPwubtU8F5Qc'

TEST_SEQ_SMALL = 0
TEST_SEQ_ONE = 1
TEST_SEQ_NORMAL = 2
