#! /usr/bin/env python3
"""
Convenience script for calling the zeno command line interface (CLI). For now,
the CLI is designed for experimenting with the Zeno Byzantine Fault Tolerant
Protocol, and not for creating a live consensus pool. For that, it's as simple
as defining a node registry, creating a looper, creating a node, and running it.
See the example folder or the tutorial folder.

$ scripts/cli

or supply a command to be executed first

$ scripts/cli "new nodes all"

"""
import sys
from configparser import ConfigParser
from tempfile import TemporaryDirectory

from zeno.cli.cli import Cli
from zeno.common.looper import Looper


def run_cli():

    commands = sys.argv[1:]

    with Looper(debug=False) as looper:
        with TemporaryDirectory() as tmpdir:
            cfg = ConfigParser()
            cfg.optionxform = str
            cfg.read('scripts/node_reg.conf')

            nodeReg = Cli.loadNodeReg(cfg)
            cliNodeReg = Cli.loadCliNodeReg(cfg)

            cli = Cli(looper=looper,
                      tmpdir=tmpdir,
                      nodeReg=nodeReg,
                      cliNodeReg=cliNodeReg,
                      logFileName='log/cli.log')

            looper.run(cli.shell(*commands))


if __name__ == '__main__':
    run_cli()
