#! /usr/bin/env python3

import argparse
from sys import argv

import os.path

from plenum.common.script_helper import initKeep, printStewardGenesisTrans
from plenum.common.util import getConfig

config = getConfig()
keepDir = os.path.expanduser(config.baseDir)


if __name__ == "__main__":
    if not os.path.exists(keepDir):
        os.makedirs(keepDir, exist_ok=True)

    parser = argparse.ArgumentParser(
        description="Generate steward key")

    parser.add_argument('name', action="store")
    parser.add_argument('--seeds', required=False, type=str, nargs=2, help='seeds for keypairs')
    parser.add_argument('--force', help='overrides keys', action='store_true')

    args = parser.parse_args()
    name = argv[1]

    # Initialize node stack
    pubkey, verkey = None, None
    privSeed = None
    signSeed = None
    if args.seeds:
        privSeed, signSeed = args.seeds[0], args.seeds[1]

    try:
        pubkey, verkey = initKeep(keepDir, name, privSeed, signSeed, args.force)
    except Exception as ex:
        print(ex)
        exit()

    # Print genesis transaction commands
    try:
        printStewardGenesisTrans(config.baseDir, args.name, verkey, pubkey)
    except Exception as ex:
        print(ex)
        exit()
