#! /usr/bin/env python3

from plenum.common.test_network_setup import TestNetworkSetup
from plenum.common.txn_util import getTxnOrderedFields
from plenum.common.config_util import getConfig

config = getConfig()
portsStart = 9600
nodeParamsFileName = 'plenum.env'


if __name__ == "__main__":
    TestNetworkSetup.bootstrapTestNodes(config, portsStart, nodeParamsFileName,
                                        getTxnOrderedFields())


# Usages:
# generate_plenum_pool_transactions --nodes=1 --clients=1 --nodeNum=1
# generate_plenum_pool_transactions --nodes=4 --clients=1 --nodeNum=1 --appendToLedgers
