#! /usr/bin/env python3

import argparse

from plenum.common.script_helper import initKeep, getOldAddNewGenStewardCommand, getOldAddNewGenNodeCommand, \
    buildKeepDirIfNotExists
from plenum.common.types import CLIENT_STACK_SUFFIX
from plenum.common.util import getConfig

config = getConfig()


def printGenesisTrans(type, name, verkey, pubkey, stewardverkey, nodeip, nodeport):
    if type == 'steward':
        print('\n' + getOldAddNewGenStewardCommand(name, verkey, pubkey))
    elif type == 'node':
        print('\n' + getOldAddNewGenNodeCommand(name, verkey, pubkey,
                                                stewardverkey, nodeip, nodeport,
                                                None, None))


if __name__ == "__main__":
    buildKeepDirIfNotExists(config.baseDir)

    parser = argparse.ArgumentParser(
        description="Generate keys for a node's stacks "
                    "by taking the node's name and 2 "
                    "seed values")

    parser.add_argument('--type', required=True, help='steward or node')
    parser.add_argument('--stewardverkey', required=False, help="in case of node, requires steward's ver key")
    parser.add_argument('--nodeip', required=False, help="node ip address")
    parser.add_argument('--nodeport', required=False, help="node port")
    parser.add_argument('--name', required=True, help='node name')
    parser.add_argument('--seeds', required=True, type=str, nargs=2, help='seeds for keypairs')
    parser.add_argument('--print_gen_txn', help='overrides keys', action='store_true')
    parser.add_argument('--force', help='overrides keys', action='store_true')

    args = parser.parse_args()

    # Initialize node stack
    print("For node stack, stack name is", args.name)
    pubkey, verkey = None, None

    try:
        pubkey, verkey = initKeep(config.baseDir, args.name, args.seeds[0], args.seeds[1], args.force)
    except Exception as ex:
        print(ex)
        exit()

    # Initialize client stack
    print("For client stack, stack name is", args.name + CLIENT_STACK_SUFFIX)
    try:
        initKeep(config.baseDir, args.name + CLIENT_STACK_SUFFIX, args.seeds[0],
             args.seeds[1], args.force)
    except Exception as ex:
        print(ex)
        exit()

    # Print genesis transaction commands
    try:
        if args.print_gen_txn:
            printGenesisTrans(args.type, args.name, verkey, pubkey,
                              args.stewardverkey, args.nodeip, args.nodeport)
    except Exception as ex:
        print(ex)
        exit()
