#! /usr/bin/env python3

# TODO: Read ip and port as command line args

import socket

UDP_IP = "0.0.0.0"
UDP_PORT = 9735
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))
while True:
    data, addr = sock.recvfrom(1024)
    print("received from address:", addr)
    print("received message:", data)
