
# Number of node stack messages processed in one looper run
NODE_STACK_MESSAGES_PROCESSED = b'NODE_STACK_MESSAGES_PROCESSED'
# Number of client stack messages processed in one looper run
CLIENT_STACK_MESSAGES_PROCESSED = b'CLIENT_STACK_MESSAGES_PROCESSED'
# Seconds passed between looper runs
LOOPER_RUN_TIME_SPENT = b'LOOPER_RUN_TIME_SPENT'
# Number of requests in one 3PC batch
BACKUP_THREE_PC_BATCH_SIZE = b'BACKUP_THREE_PC_BATCH_SIZE'
# Number of messages in one tranport batch
TRANSPORT_BATCH_SIZE = b'TRANSPORT_BATCH_SIZE'
# Outgoing node message size, bytes
OUTGOING_NODE_MESSAGE_SIZE = b'OUTGOING_NODE_MESSAGE_SIZE'
# Incoming node message size, bytes
INCOMING_NODE_MESSAGE_SIZE = b'INCOMING_NODE_MESSAGE_SIZE'
# Outgoing client message size, bytes
OUTGOING_CLIENT_MESSAGE_SIZE = b'OUTGOING_CLIENT_MESSAGE_SIZE'
# Incoming client message size, bytes
INCOMING_CLIENT_MESSAGE_SIZE = b'INCOMING_CLIENT_MESSAGE_SIZE'
# Number of requests ordered
BACKUP_ORDERED_BATCH_SIZE = b'BACKUP_ORDERED_BATCH_SIZE'
# Time spent on requests processing on backup instances
BACKUP_REQUEST_PROCESSING_TIME = b'BACKUP_REQUEST_PROCESSING_TIME'
# Number of requests in one 3PC batch created on master instance
THREE_PC_BATCH_SIZE = b'THREE_PC_BATCH_SIZE'
# Number of requests ordered on master instance
ORDERED_BATCH_SIZE = b'ORDERED_BATCH_SIZE'
# Time spent on requests processing on master instance
REQUEST_PROCESSING_TIME = b'REQUEST_PROCESSING_TIME'
# Number of invalid request for master
ORDERED_BATCH_INVALID_COUNT = b'ORDERED_BATCH_INVALID_COUNT'
# Number of txns sent through catchup
CATCHUP_TXNS_SENT = b'CATCHUP_TXNS_SENT'
# Number of txns received through catchup
CATCHUP_TXNS_RECEIVED = b'CATCHUP_TXNS_RECEIVED'

# Average throughput measured by monitor on backup instances
BACKUP_MONITOR_AVG_THROUGHPUT = b'BACKUP_MONITOR_AVG_THROUGHPUT'
# Average latency measured by monitor on backup instances
BACKUP_MONITOR_AVG_LATENCY = b'BACKUP_MONITOR_AVG_LATENCY'
# Average throughput measured by monitor on master instance
MONITOR_AVG_THROUGHPUT = b'MONITOR_AVG_THROUGHPUT'
# Average latency measured by monitor on master instance
MONITOR_AVG_LATENCY = b'MONITOR_AVG_LATENCY'

# Node incoming request queue size
REQUEST_QUEUE_SIZE = b'REQUEST_QUEUE_SIZE'
FINALISED_REQUEST_QUEUE_SIZE = b'FINALISED_REQUEST_QUEUE_SIZE'
MONITOR_REQUEST_QUEUE_SIZE = b'MONITOR_REQUEST_QUEUE_SIZE'
MONITOR_UNORDERED_REQUEST_QUEUE_SIZE = b'MONITOR_UNORDERED_REQUEST_QUEUE_SIZE'

# System statistics
AVAILABLE_RAM_SIZE = b'AVAILABLE_RAM_SIZE'
NODE_RSS_SIZE = b'NODE_RSS_SIZE'
NODE_VMS_SIZE = b'NODE_VMS_SIZE'
CONNECTED_CLIENTS_NUM = b'CONNECTED_CLIENTS_NUM'
GC_TRACKED_OBJECTS = b'GC_TRACKED_OBJECTS'
GC_TIME_GEN = b'GC_TIME_GEN'
GC_UNCOLLECTABLE_OBJECTS = b'GC_UNCOLLECTABLE_OBJECTS'
GC_TOTAL_COLLECTED_OBJECTS = b'GC_TOTAL_COLLECTED_OBJECTS'
GC_COLLECTED_OBJECTS_GEN = b'GC_COLLECTED_OBJECTS_GEN'
CURRENT_VIEW = b'CURRENT_VIEW'
VIEW_CHANGE_IN_PROGRESS = b'VIEW_CHANGE_IN_PROGRESS'
NODE_STATUS = b'NODE_STATUS'
CONNECTED_NODES_NUM = b'CONNECTED_NODES_NUM'
BLACKLISTED_NODES_NUM = b'BLACKLISTED_NODES_NUM'
REPLICA_COUNT = b'REPLICA_COUNT'
POOL_LEDGER_SIZE = b'POOL_LEDGER_SIZE'
DOMAIN_LEDGER_SIZE = b'DOMAIN_LEDGER_SIZE'
CONFIG_LEDGER_SIZE = b'CONFIG_LEDGER_SIZE'
POOL_LEDGER_UNCOMMITTED_SIZE = b'POOL_LEDGER_UNCOMMITTED_SIZE'
DOMAIN_LEDGER_UNCOMMITTED_SIZE = b'DOMAIN_LEDGER_UNCOMMITTED_SIZE'
CONFIG_LEDGER_UNCOMMITTED_SIZE = b'CONFIG_LEDGER_UNCOMMITTED_SIZE'
PROPAGATES_PHASE_REQ_TIMEOUTS = b'PROPAGATES_PHASE_REQ_TIMEOUTS'
ORDERING_PHASE_REQ_TIMEOUTS = b'ORDERING_PHASE_REQ_TIMEOUTS'

# Node service statistics
NODE_PROD_TIME = b'NODE_PROD_TIME'
SERVICE_REPLICAS_TIME = b'SERVICE_REPLICAS_TIME'
SERVICE_NODE_MSGS_TIME = b'SERVICE_NODE_MSGS_TIME'
SERVICE_CLIENT_MSGS_TIME = b'SERVICE_CLIENT_MSGS_TIME'
SERVICE_NODE_ACTIONS_TIME = b'SERVICE_NODE_ACTIONS_TIME'
SERVICE_LEDGER_MANAGER_TIME = b'SERVICE_LEDGER_MANAGER_TIME'
SERVICE_VIEW_CHANGER_TIME = b'SERVICE_VIEW_CHANGER_TIME'
SERVICE_OBSERVABLE_TIME = b'SERVICE_OBSERVABLE_TIME'
SERVICE_OBSERVER_TIME = b'SERVICE_OBSERVER_TIME'
FLUSH_OUTBOXES_TIME = b'FLUSH_OUTBOXES_TIME'
SERVICE_NODE_LIFECYCLE_TIME = b'SERVICE_NODE_LIFECYCLE_TIME'
SERVICE_CLIENT_STACK_TIME = b'SERVICE_CLIENT_STACK_TIME'
SERVICE_MONITOR_ACTIONS_TIME = b'SERVICE_MONITOR_ACTIONS_TIME'

# Node specific metrics
SERVICE_NODE_STACK_TIME = b'SERVICE_NODE_STACK_TIME'
PROCESS_NODE_INBOX_TIME = b'PROCESS_NODE_INBOX_TIME'
SEND_TO_REPLICA_TIME = b'SEND_TO_REPLICA_TIME'
NODE_CHECK_PERFORMANCE_TIME = b'NODE_CHECK_PERFORMANCE_TIME'
NODE_CHECK_NODE_REQUEST_SPIKE = b'NODE_CHECK_NODE_REQUEST_SPIKE'
UNPACK_BATCH_TIME = b'UNPACK_BATCH_TIME'
VERIFY_SIGNATURE_TIME = b'VERIFY_SIGNATURE_TIME'
SERVICE_REPLICAS_OUTBOX_TIME = b'SERVICE_REPLICAS_OUTBOX_TIME'
NODE_SEND_TIME = b'NODE_SEND_TIME'
NODE_SEND_REJECT_TIME = b'NODE_SEND_REJECT_TIME'
VALIDATE_NODE_MSG_TIME = b'VALIDATE_NODE_MSG_TIME'
INT_VALIDATE_NODE_MSG_TIME = b'INT_VALIDATE_NODE_MSG_TIME'
PROCESS_ORDERED_TIME = b'PROCESS_ORDERED_TIME'
MONITOR_REQUEST_ORDERED_TIME = b'MONITOR_REQUEST_ORDERED_TIME'
EXECUTE_BATCH_TIME = b'EXECUTE_BATCH_TIME'

# Replica specific metrics
SERVICE_REPLICA_QUEUES_TIME = b'SERVICE_REPLICA_QUEUES_TIME'
SERVICE_BACKUP_REPLICAS_QUEUES_TIME = b'SERVICE_BACKUP_REPLICAS_QUEUES_TIME'

# Master replica message statistics
PROCESS_PREPREPARE_TIME = b'PROCESS_PREPREPARE_TIME'
PROCESS_PREPARE_TIME = b'PROCESS_PREPARE_TIME'
PROCESS_COMMIT_TIME = b'PROCESS_COMMIT_TIME'
PROCESS_CHECKPOINT_TIME = b'PROCESS_CHECKPOINT_TIME'
SEND_PREPREPARE_TIME = b'SEND_PREPREPARE_TIME'
SEND_PREPARE_TIME = b'SEND_PREPARE_TIME'
SEND_COMMIT_TIME = b'SEND_COMMIT_TIME'
SEND_CHECKPOINT_TIME = b'SEND_CHECKPOINT_TIME'
CREATE_3PC_BATCH_TIME = b'CREATE_3PC_BATCH_TIME'
ORDER_3PC_BATCH_TIME = b'ORDER_3PC_BATCH_TIME'

# Backup replica message statistics
BACKUP_PROCESS_PREPREPARE_TIME = b'BACKUP_PROCESS_PREPREPARE_TIME'
BACKUP_PROCESS_PREPARE_TIME = b'BACKUP_PROCESS_PREPARE_TIME'
BACKUP_PROCESS_COMMIT_TIME = b'BACKUP_PROCESS_COMMIT_TIME'
BACKUP_PROCESS_CHECKPOINT_TIME = b'BACKUP_PROCESS_CHECKPOINT_TIME'
BACKUP_SEND_PREPREPARE_TIME = b'BACKUP_SEND_PREPREPARE_TIME'
BACKUP_SEND_PREPARE_TIME = b'BACKUP_SEND_PREPARE_TIME'
BACKUP_SEND_COMMIT_TIME = b'BACKUP_SEND_COMMIT_TIME'
BACKUP_SEND_CHECKPOINT_TIME = b'BACKUP_SEND_CHECKPOINT_TIME'
BACKUP_CREATE_3PC_BATCH_TIME = b'BACKUP_CREATE_3PC_BATCH_TIME'
BACKUP_ORDER_3PC_BATCH_TIME = b'BACKUP_ORDER_3PC_BATCH_TIME'

# Node message statistics
PROCESS_PROPAGATE_TIME = b'PROCESS_PROPAGATE_TIME'
PROCESS_MESSAGE_REQ_TIME = b'PROCESS_MESSAGE_REQ_TIME'
PROCESS_MESSAGE_REP_TIME = b'PROCESS_MESSAGE_REP_TIME'
PROCESS_LEDGER_STATUS_TIME = b'PROCESS_LEDGER_STATUS_TIME'
PROCESS_CONSISTENCY_PROOF_TIME = b'PROCESS_CONSISTENCY_PROOF_TIME'
PROCESS_CATCHUP_REQ_TIME = b'PROCESS_CATCHUP_REQ_TIME'
PROCESS_CATCHUP_REP_TIME = b'PROCESS_CATCHUP_REP_TIME'
PROCESS_REQUEST_TIME = b'PROCESS_REQUEST_TIME'
SEND_PROPAGATE_TIME = b'SEND_PROPAGATE_TIME'
SEND_MESSAGE_REQ_TIME = b'SEND_MESSAGE_REQ_TIME'
SEND_MESSAGE_REP_TIME = b'SEND_MESSAGE_REP_TIME'

# BLS statistics
BLS_VALIDATE_PREPREPARE_TIME = b'BLS_VALIDATE_PREPREPARE_TIME'
BLS_VALIDATE_COMMIT_TIME = b'BLS_VALIDATE_COMMIT_TIME'
BLS_UPDATE_PREPREPARE_TIME = b'BLS_UPDATE_PREPREPARE_TIME'
BLS_UPDATE_COMMIT_TIME = b'BLS_UPDATE_COMMIT_TIME'

# KV storages metrics
_STORAGE_READERS = b'_READERS'
_STORAGE_TABLES_NUM = b'_TABLES_NUM'
_STORAGE_TABLES_SIZE = b'_TABLES_SIZE'

STORAGE_IDR_CACHE = b'STORAGE_IDR_CACHE'
STORAGE_ATTRIBUTE_STORE = b'STORAGE_ATTRIBUTE_STORE'
STORAGE_POOL_STATE = b'STORAGE_POOL_STATE'
STORAGE_DOMAIN_STATE = b'STORAGE_DOMAIN_STATE'
STORAGE_CONFIG_STATE = b'STORAGE_CONFIG_STATE'
STORAGE_POOL_MANAGER = b'STORAGE_POOL_MANAGER'
STORAGE_BLS_BFT = b'STORAGE_BLS_BFT'
STORAGE_SEQ_NO = b'STORAGE_SEQ_NO'
STORAGE_METRICS = b'STORAGE_METRICS'
