#!/bin/bash

# disabling auto update for indy-plenum package
apt-mark hold indy-plenum

# Automatically added from template:
if which py3compile >/dev/null 2>&1; then
	py3compile -O -p indy-plenum /usr/local/lib/python3.5/dist-packages/
fi

# End automatically added section
