@startuml

box "Alice" #LightBlue
actor "Agent" as A
participant "Wallet" as AW
endbox

box "Faber College" #LightYellow
actor "Agent" as F
participant "Wallet" as FW
endbox

box "Acme Corp" #LightBlue
actor "Agent" as AC
participant "Wallet" as ACW
endbox

box "Thrift Bank" #LightYellow
actor "Agent" as T
participant "Wallet" as TW
endbox

participant "Ledger" as L

box "Government" #LightBlue
actor "Agent" as G
participant "Wallet" as GW
endbox


=== Getting Trust Anchor credentials for Faber, Acme, Thrift and Government  ==


=== Credential Schemas Setup ==
G->GW: Create "Job-Certificate" Schema
G->L: Send Schema for "Job-Certificate" Schema
G->GW: Create "Transcript" Schema
G->L: Send Schema for "Transcript" Schema

===  Credential Definitions Setup ==
F->L: Send GetSchema for "Transcript" Schema
F->FW: Create and store "Faber Transcript" Credential Definition
F->L: Send CredDef for "Faber Transcript" Credential Definition

AC->L: Send GetSchema for "Job-Certificate" Schema
AC->ACW: Create and store "Acme Job-Certificate" Credential Definition
AC->L: Send CredDef for "Acme Job-Certificate" Credential Definition

=== Getting Transcript with Faber ==

F->A: Send authcrypted "Alice Faber Transcript" Credential Offer
A->AW: Create and store "Alice" Master Secret
A->L: Send GetSchema for "Transcript" Schema
A->L: Send GetCredDef for "Faber Transcript" Credential Definition
A->AW: Create "Alice Faber Transcript" Credential Request
A->F: Send authcrypted "Alice Faber Transcript" Credential Request
F->F: Create "Alice Faber Transcript" Credential
F->A: Send authcrypted "Alice Faber Transcript" Credential
A->AW: Store "Alice Faber Transcript" Credential

=== Apply for the job with Acme ==

== Apply for the job with Acme - Job-Application proving ==
AC->A: Send authcrypted "Job-Application" Proof Request
A->AW: Get credentials for "Job-Application" Proof Request
AW->A: "Alice Faber Transcript" Credential
A->L: Send GetSchema for "Transcript" Schema
A->L: Send GetCredDef for "Faber Transcript" Credential Definition
A->A: Create "Alice Job-Application" Proof
A->AC: Send authcrypted "Alice Job-Application" Proof
AC->L: Send GetSchema for "Transcript" Schema
AC->L: Send GetCredDef for "Faber Transcript" Credential Definition
AC->AC: Verify "Alice Job-Application" Proof

== Apply for the job with Acme - Getting Job-Certificate Credential ==
AC->A: Send authcrypted "Alice Acme Job-Certificate" Credential Offer
A->L: Send GetSchema for "Job-Certificate" Schema
A->L: Send GetCredDef for "Acme Job-Certificate" Credential Definition
A->AW: Create "Alice Acme Job-Certificate" Credential Request
A->AC: Send authcrypted "Alice Acme Job-Certificate" Credential Request
AC->AC: Create "Alice Acme Job-Certificate" Credential
AC->A: Send authcrypted "Alice Acme Job-Certificate" Credential
A->AW: Store "Alice Acme Job-Certificate" Credential

=== Apply for the loan with Thrift ==

== Apply for the loan with Thrift - Employment History proving  ==
T->A: Send authcrypted "Loan-Application-Basic" Proof Request
A->AW: Get credentials for "Loan-Application-Basic" Proof Request
AW->A: "Alice Acme Job-Certificate" Credential
A->L: Send GetSchema for "Job-Certificate" Schema
A->L: Send GetCredDef for "Acme Job-Certificate" Credential Definition
A->A: Create "Loan-Application-Basic" Proof
A->T: Send "Loan-Application-Basic" Proof
T->L: Send GetSchema for "Job-Certificate" Schema
T->L: Send GetCredDef for "Acme Job-Certificate" Credential Definition
T->T: Verify "Loan-Application-Basic" Proof

== Apply for the loan with Thrift - Loan-Application-KYC proving  ==
T->A: Send authcrypted "Loan-Application-KYC" Proof Request
A->AW: Get credentials for "Loan-Application-KYC" Proof Request
AW->A: "Alice Faber Transcript and Alice Acme Job-Certificate" Credential
A->L: Send GetSchema for "Transcript" Schema
A->L: Send GetCredDef for "Faber Transcript" Credential Definition
A->L: Send GetSchema for "Job-Certificate" Schema
A->L: Send GetCredDef for "Acme Job-Certificate" Credential Definition
A->A: Create "Loan-Application-KYC" Proof
A->T: Send "Loan-Application-KYC" Proof
T->L: Send GetSchema for "Transcript" Schema
T->L: Send GetCredDef for "Faber Transcript" Credential Definition
T->L: Send GetSchema for "Job-Certificate" Schema
T->L: Send GetCredDef for "Acme Job-Certificate" Credential Definition
T->T: Verify "Loan-Application-KYC" Proof

@enduml