name: Triggered by set Tag

on:
  push:
    tags:
      - setRelease-v**

jobs:
  taginfos:
    name: get Tag infos
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-release-info.outputs.version }}
      versionTag: ${{ steps.get-release-info.outputs.versionTag }}
      prBranch: ${{ steps.get-release-info.outputs.prBranch }}
      BASE: ${{ steps.get-branch.outputs.branch }}
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: extract branch
        id: get-branch
        uses: hyperledger/indy-shared-gha/.github/actions/branch-from-tag@v2
        with:
          tag: ${{ github.ref }}
      - name: get-release-info
        id: get-release-info
        uses: hyperledger/indy-shared-gha/.github/actions/get-release-info@v2
        with:
          versionString: "${{ github.ref }}"

  bump_version:
    name: Bump Version Number
    needs: taginfos
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install deps for version change
        run: pip install base58 \
                      importlib_metadata==3.10.1 \
                      packaging \
                      python-dateutil \
                      msgpack-python \
                      jsonpickle
      - name: Prepare package and set version
        run: |
          ./bump_version.sh ${{ needs.taginfos.outputs.VERSION }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          author: ${{ github.actor }} <${{ github.event.pusher.email }}>
          committer: ${{ github.actor }} <${{ github.event.pusher.email }}>
          signoff: true
          commit-message: Update Version number for v${{ needs.taginfos.outputs.version }}
          base: ${{ needs.taginfos.outputs.BASE }}
          branch: ${{ needs.taginfos.outputs.prBranch }}
          title: "[${{ needs.taginfos.outputs.versionTag }}] - Update Version Number for Release"
          body: "[${{ needs.taginfos.outputs.versionTag }}] - Update Version number for Release"
          delete-branch: true
          token: ${{ secrets.BOT_PR_PAT }}
